/**
 * Centralized TanStack Query key factory.
 *
 * Components that share the same key automatically share one in-flight
 * request and one cache entry — eliminating duplicate polls.
 */
export const qk = {
  projects:             ()                              => ["projects"]                       as const,
  conversations:        (projectId: string | null, limit: number) => ["conversations", projectId, limit] as const,
  allRuns:              (limit: number)                 => ["allRuns", limit]                 as const,
  runsForConversation:  (convId: string | null)         => ["runsForConversation", convId]    as const,
  recentRuns:           (limit: number)                 => ["recentRuns", limit]              as const,
  conversation:         (id: string | null)             => ["conversation", id]               as const,
  connections:          ()                              => ["connections"]                    as const,
  providers:            ()                              => ["providers"]                      as const,
  editors:              ()                              => ["editors"]                        as const,
  llmSelection:         ()                              => ["llmSelection"]                   as const,
  models:               (kind: string)                  => ["models", kind]                   as const,
  workspace:            ()                              => ["workspace"]                      as const,
  doctor:               ()                              => ["doctor"]                         as const,
  capabilities:         ()                              => ["capabilities"]                   as const,
  issues:               (projectId: string | null)      => ["issues", projectId]              as const,
  issueBoard:           (projectId: string | null)      => ["issueBoard", projectId]          as const,
  tasks:                (convId: string | null)         => ["tasks", convId]                  as const,
  panelData:            (runId: string | null)          => ["panelData", "run", runId]        as const,
  projectPanelData:     (root: string | null)           => ["panelData", "project", root]     as const,
  prStatus:             (runId: string | null)          => ["prStatus", "run", runId]          as const,
  projectPrStatus:      (root: string | null)           => ["prStatus", "project", root]       as const,
  isGitRepo:            (root: string | null)           => ["isGitRepo", root]                as const,
  openIssueCount:       (projectId: string | null)      => ["openIssueCount", projectId]      as const,
  sessions:             (runId: string)                 => ["sessions", runId]                as const,
  planSteps:            (runId: string)                 => ["planSteps", runId]               as const,
  subtasks:             (runId: string)                 => ["subtasks", runId]                as const,
  locks:                (runId: string)                 => ["locks", runId]                   as const,
  mergeQueue:           (runId: string)                 => ["mergeQueue", runId]              as const,
  signals:              (runId: string)                 => ["signals", runId]                 as const,
  checkpoints:          (runId: string)                 => ["checkpoints", runId]             as const,
  runMessages:          (runId: string)                 => ["runMessages", runId]             as const,
  events:               (runId: string | null)          => ["events", runId]                  as const,
  messages:             (convId: string, limit: number) => ["messages", convId, limit]        as const,
  balance:              ()                              => ["balance"]                        as const,
  config:               ()                              => ["config"]                         as const,
  projectRoot:          ()                              => ["projectRoot"]                    as const,
  worktrees:            ()                              => ["worktrees"]                      as const,
  hooks:                ()                              => ["hooks"]                          as const,
  agentCatalog:         ()                              => ["agentCatalog"]                   as const,
  defaultProvider:      ()                              => ["defaultProvider"]                as const,
  runArtifacts:         (runId: string)                 => ["runArtifacts", runId]            as const,
  qaMessages:           (runId: string)                 => ["qaMessages", runId]              as const,
  automations:          (projectId: string | null)      => ["automations", projectId]         as const,
  automationSteps:      (automationId: string | null)   => ["automationSteps", automationId]  as const,
  automationRuns:       (automationId: string | null)   => ["automationRuns", automationId]   as const,
  automationRunSteps:   (runId: string | null)          => ["automationRunSteps", runId]      as const,
  chatterThreads:       (convId: string)                => ["chatter", "threads", convId]     as const,
  chatterLog:           (convId: string, chatterId: string) => ["chatter", "log", convId, chatterId] as const,
  chatSettings:         (convId: string)                => ["chatter", "settings", convId]    as const,

  // Grove Graph
  graphs:               (conversationId: string)        => ["graphs", "list", conversationId]       as const,
  graphDetail:          (graphId: string)               => ["graphs", "detail", graphId]            as const,
  graphActive:          (conversationId: string)        => ["graphs", "active", conversationId]     as const,
  graphConfig:          (graphId: string)               => ["graphs", "config", graphId]            as const,
  graphReadySteps:      (graphId: string)               => ["graphs", "readySteps", graphId]        as const,
  graphStepFeedback:    (stepId: string)                => ["graphs", "stepFeedback", stepId]       as const,
  graphGitStatus:       (graphId: string)               => ["graphs", "gitStatus", graphId]         as const,
  graphPhases:          (graphId: string)               => ["graphs", "phases", graphId]            as const,
  graphSteps:           (phaseId: string)               => ["graphs", "steps", phaseId]             as const,
  graphPendingValidation: (graphId: string)             => ["graphs", "pendingValidation", graphId] as const,
  graphDocument:          (graphId: string)             => ["graphs", "document", graphId]          as const,
} as const;
